name: antonkoetzler_github_io
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  myoro_flutter_library:
    git:
      url: git@github.com:antonkoetzler/myoro_flutter_library
    # path: ../../myoro_flutter_library
  intl: any
  flutter_emoji: ^2.5.1
  flutter_svg: ^2.0.17
  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
