name: antonkoetzler_github_io
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  myoro_flutter_library:
    # git:
    #   url: git@github.com:antonkoetzler/myoro_flutter_library
    path: ../../myoro_flutter_library
  device_info_plus: ^11.2.1
  flutter_bloc: ^9.0.0
  # Conflicts with flutter
  faker: ^2.1.0
  # Conflict with flutter-test
  collection: 1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
